services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://user:password@db:5432/car_db
    depends_on:
      - db
    restart: on-failure

  
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=car_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  
